apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-pdb
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: cobalto-soc
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: elasticsearch
