apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: cobalto-soc
  app.kubernetes.io/managed-by: kustomize
