apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST

  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch.svc.cluster.local:9200
    database: "wazuh-alerts-*"
    editable: true
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
      indexPattern: "[wazuh-alerts-]YYYY.MM.DD"
      interval: "daily"
    user: ""
    secureJsonData:
      password: ""