apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: qdrant
  labels:
    app.kubernetes.io/name: qdrant
data:
  config.yaml: |
    storage:
      storage_path: /qdrant/storage
      snapshots_path: /qdrant/snapshots
    service:
      grpc_port: 6334
      http_port: 6333
    performance:
      max_search_threads: 0
      max_optimization_threads: 1
      max_global_score_sorting_threads: 1
    hnsw_index:
      m: 16
      ef_construct: 100
      full_scan_threshold: 10000
    optimizers:
      deleted_threshold: 0.2
      indexing_threshold: 20000
