apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/version: "v1.9.0"
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qdrant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
              name: http
              protocol: TCP
            - containerPort: 6334
              name: grpc
              protocol: TCP
          env:
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
            - name: QDRANT__SERVICE__HTTP_PORT
              value: "6333"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
            - name: config
              mountPath: /qdrant/config/config.yaml
              subPath: config.yaml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6333
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: qdrant-config
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
