apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thehive-pdb
  namespace: thehive
  labels:
    app.kubernetes.io/name: thehive
    app.kubernetes.io/part-of: cobalto-soc
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: thehive
