apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
data:
  db-host: "rds-endpoint"
  db-port: "5432"
  db-name: "n8ndb"
  basic-auth-active: "true"
  webhook-url: "https://n8n.example.com/"
