apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh-indexer
    app.kubernetes.io/part-of: wazuh
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wazuh-indexer
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
