apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - manager-deployment.yaml
  - indexer-statefulset.yaml
  - dashboard-deployment.yaml
  - manager-service.yaml
  - indexer-service.yaml
  - dashboard-service.yaml
  - configmap.yaml
